
name: cli tool

on:
  push:
    tags:
      - "*" # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  NODE_VERSION: "14.x"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm i
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate ChangeLog
        id: changelog
        uses: git-chglog/git-chglog-action@v1
        with:
          config-path: .github/.chglog.yml
          output: ./docs/CHANGELOG.md

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false

      - name: Commit docs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm run build:docs
          git add .
          git commit -m "Update docs" || exit 0  # 如果没有更改则退出
          git push

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: |
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
